= VoltLink™
:toc:
:sectnums:
:sectnumlevels: 4


* Current version: *0.1*
* link:./CHANGELOG.adoc[Changelog]

'''

== Original author's README - ish

link:https://github.com/voltlog/VoltLink[Original repository]

VoltLink™ is a USB to serial adapter board based on the popular CP2102N chip with built-in ESP32 auto-reset circuitry.
When compared to the cheap modules you can get from Aliexpress this adapter is reliable & flexible at the same time.
Reliable because it's based on a well known usb to serial adapter chip sourced from a known supplier and flexible because you have the ESP32 IO & EN pin auto-reset circuit built-in so there is no need to implement this on the target board.

You have the option of connecting through the VoltLink connector which is a JST-SH 1.0mm pitch 6 pin connector that saves space on the target board or via standard 0.1 inch pin header.

If you would like to order one of these adapters ready assembled, check out my link:https://www.tindie.com/products/23076/[Tindie store].

More info about this project in:

* link:https://www.youtube.com/watch?v=bfN77jT1SVE[Voltlog #356 - VoltLink A Fancy USB Serial Adapter (ESP32 Programmer)].
* link:https://www.youtube.com/watch?v=roMjPoaFAZ8[Voltlog #357 - A fatal error occurred: Failed to connect to ESP32]
* link:https://www.youtube.com/watch?v=hDepAs7ljAk[Voltlog #396 - VoltLink™ revB CP2102N USB Serial Bridge & ESP32 Programmer]

== Automated exporting
=== Installation
==== KiBot
link:https://github.com/INTI-CMNB/kibot#installation-using-pip[Installation]:

* `pip install --no-compile kibot`
(on Windows you probably need to install it in `KiCad Command Prompt`)

* On Arch Linux you can install it with: `paru -S kibot-git`
** You may need to install `pcbdraw-git` in case of
`module 'pcbnew' has no attribute 'PLOTTEXTMODE_STROKE'` error
(try to run `pcbnew --version` to be sure that program runs correctly)

==== recordmydesktop
* Needed only if running `kibot -vvv`
* Arch Linux: `sudo pacman -S recordmydesktop`

== TODO
